### ISSUE TITLE
How to predict

### ISSUE THREAD

**Issue by happyTonakai** [james34602/Neural-Network-Quadraphonic-Upmix#1]
Given an input feature of size (2, 1), the network's output is a scalar. How do I predict the upmixed spectrum using this output? Thanks.

**Comment by james34602** [comment]
You would need to compute the model for each frequency bins.
For example, 512 FFT is 257 bins, run the model 257 times.

The model output a probability 1 bin at a time.

**Comment by happyTonakai** [comment]
Thank you for response. I know I have to run the model for each FFT bin using the feature extracted from `XL[k]` and `XR[k]` and then I get a vector of time-frequency mask, let's say it's `a[k]`

But what should I do to calculate the spectrum of output signal `Y[k]`? It seems to be something like `YL[k] = XL[k] * a[k]`, but I'm not sure.

**Comment by james34602** [comment]
yes, you are right, it's a plain magnitude real valued mask.

**Comment by happyTonakai** [comment]
OK. Thank you very much.

**Comment by james34602** [comment]
This repo is suppose to demonstrate the fitting capability of simple nonlinear model(Aka, neural network).

From traditional point of view, it's just about how to make use of magnitude difference and phase difference.

Check out this repo if you really want a high quality upmix for (3.1, 5.1, 7.1) [https://github.com/james34602/LUTSurround](https://github.com/james34602/LUTSurround)
